"""new body_html col

Revision ID: 30eabe519066
Revises: d2873dc34213
Create Date: 2016-01-13 08:21:42.069190

"""

# revision identifiers, used by Alembic.
revision = '30eabe519066'
down_revision = 'd2873dc34213'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
