"""Added confirmed column

Revision ID: 8866e5653475
Revises: ec41b88d502f
Create Date: 2016-01-11 10:26:28.274615

"""

# revision identifiers, used by Alembic.
revision = '8866e5653475'
down_revision = 'ec41b88d502f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
