"""added avatar_hash to User

Revision ID: fd3a412551ee
Revises: 929ce46d756a
Create Date: 2016-01-12 19:02:50.460103

"""

# revision identifiers, used by Alembic.
revision = 'fd3a412551ee'
down_revision = '929ce46d756a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
